baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en
name: 'Craft CMS - Initial'
primary: true
siteGroup: 0016e05e-2f77-4dcb-ae4d-e0fcfd73cf07 # Craft CMS Initial
sortOrder: 1
