baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en
name: 'Springlane Magazine'
primary: true
siteGroup: 281a1ba5-e2d3-48a4-b9cb-ccac6a39f8c5 # Springlane
sortOrder: 1
