dateModified: 1617894158
email:
  fromEmail: asd@asdasd.com
  fromName: 'Craft CMS Initial'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
system:
  edition: solo
  live: false
  name: 'Davids Site'
  retryDuration: null
  schemaVersion: 3.6.6
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
