# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ symfony/skeleton ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  info:
    
    runs-on: ubuntu-latest
  
    steps:
      - name: Test User Id
        run: id -u

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Docker up
        run: docker-compose up -d

      # Runs a set of commands using the runners shell
      - name: Run composer install
        run: docker exec -t -u root webphp composer install

      - name: Run make:command
        run: docker exec -t -u root webphp php bin/console make:command david:command -n
        
        
